/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authOrgSelectionRouteImport } from './routes/(auth)/org-selection'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as LiveblocksAuthRouteImport } from './routes/liveblocks/auth'
import { Route as LiveblocksUsersRouteImport } from './routes/liveblocks/users'
import { Route as ReplaysSessionIdRouteImport } from './routes/replays/$sessionId'
import { Route as authSignInSplatRouteImport } from './routes/(auth)/sign-in.$'
import { Route as authSignUpSplatRouteImport } from './routes/(auth)/sign-up.$'
import { Route as dashboardWorkflowsIdIndexRouteImport } from './routes/(dashboard)/workflows/$id/index'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authOrgSelectionRoute = authOrgSelectionRouteImport.update({
  id: '/org-selection',
  path: '/org-selection',
  getParentRoute: () => authRouteRoute,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const LiveblocksAuthRoute = LiveblocksAuthRouteImport.update({
  id: '/liveblocks/auth',
  path: '/liveblocks/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveblocksUsersRoute = LiveblocksUsersRouteImport.update({
  id: '/liveblocks/users',
  path: '/liveblocks/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysSessionIdRoute = ReplaysSessionIdRouteImport.update({
  id: '/replays/$sessionId',
  path: '/replays/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInSplatRoute = authSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpSplatRoute = authSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => authRouteRoute,
} as any)
const dashboardWorkflowsIdIndexRoute =
  dashboardWorkflowsIdIndexRouteImport.update({
    id: '/workflows/$id/',
    path: '/workflows/$id/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/org-selection': typeof authOrgSelectionRoute
  '/liveblocks/auth': typeof LiveblocksAuthRoute
  '/liveblocks/users': typeof LiveblocksUsersRoute
  '/replays/$sessionId': typeof ReplaysSessionIdRoute
  '/': typeof dashboardIndexRoute
  '/sign-in/$': typeof authSignInSplatRoute
  '/sign-up/$': typeof authSignUpSplatRoute
  '/workflows/$id/': typeof dashboardWorkflowsIdIndexRoute
}
export interface FileRoutesByTo {
  '/org-selection': typeof authOrgSelectionRoute
  '/liveblocks/auth': typeof LiveblocksAuthRoute
  '/liveblocks/users': typeof LiveblocksUsersRoute
  '/replays/$sessionId': typeof ReplaysSessionIdRoute
  '/': typeof dashboardIndexRoute
  '/sign-in/$': typeof authSignInSplatRoute
  '/sign-up/$': typeof authSignUpSplatRoute
  '/workflows/$id': typeof dashboardWorkflowsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(auth)/org-selection': typeof authOrgSelectionRoute
  '/liveblocks/auth': typeof LiveblocksAuthRoute
  '/liveblocks/users': typeof LiveblocksUsersRoute
  '/replays/$sessionId': typeof ReplaysSessionIdRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(auth)/sign-in/$': typeof authSignInSplatRoute
  '/(auth)/sign-up/$': typeof authSignUpSplatRoute
  '/(dashboard)/workflows/$id/': typeof dashboardWorkflowsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/org-selection'
    | '/liveblocks/auth'
    | '/liveblocks/users'
    | '/replays/$sessionId'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workflows/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/org-selection'
    | '/liveblocks/auth'
    | '/liveblocks/users'
    | '/replays/$sessionId'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workflows/$id'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(auth)/org-selection'
    | '/liveblocks/auth'
    | '/liveblocks/users'
    | '/replays/$sessionId'
    | '/(dashboard)/'
    | '/(auth)/sign-in/$'
    | '/(auth)/sign-up/$'
    | '/(dashboard)/workflows/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  LiveblocksAuthRoute: typeof LiveblocksAuthRoute
  LiveblocksUsersRoute: typeof LiveblocksUsersRoute
  ReplaysSessionIdRoute: typeof ReplaysSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/org-selection': {
      id: '/(auth)/org-selection'
      path: '/org-selection'
      fullPath: '/org-selection'
      preLoaderRoute: typeof authOrgSelectionRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/liveblocks/auth': {
      id: '/liveblocks/auth'
      path: '/liveblocks/auth'
      fullPath: '/liveblocks/auth'
      preLoaderRoute: typeof LiveblocksAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liveblocks/users': {
      id: '/liveblocks/users'
      path: '/liveblocks/users'
      fullPath: '/liveblocks/users'
      preLoaderRoute: typeof LiveblocksUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays/$sessionId': {
      id: '/replays/$sessionId'
      path: '/replays/$sessionId'
      fullPath: '/replays/$sessionId'
      preLoaderRoute: typeof ReplaysSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/$': {
      id: '/(auth)/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof authSignInSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up/$': {
      id: '/(auth)/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof authSignUpSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(dashboard)/workflows/$id/': {
      id: '/(dashboard)/workflows/$id/'
      path: '/workflows/$id'
      fullPath: '/workflows/$id/'
      preLoaderRoute: typeof dashboardWorkflowsIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authOrgSelectionRoute: typeof authOrgSelectionRoute
  authSignInSplatRoute: typeof authSignInSplatRoute
  authSignUpSplatRoute: typeof authSignUpSplatRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authOrgSelectionRoute: authOrgSelectionRoute,
  authSignInSplatRoute: authSignInSplatRoute,
  authSignUpSplatRoute: authSignUpSplatRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardWorkflowsIdIndexRoute: typeof dashboardWorkflowsIdIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardWorkflowsIdIndexRoute: dashboardWorkflowsIdIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  LiveblocksAuthRoute: LiveblocksAuthRoute,
  LiveblocksUsersRoute: LiveblocksUsersRoute,
  ReplaysSessionIdRoute: ReplaysSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
